services:
  - type: web
    name: retail-forecast-api
    runtime: python
    buildCommand: pip install -r render.requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHONPATH
        value: .
